import embedfs

fn test_generate() {
	expected := r"module main

/*
	This file is generated by embedfs module, DO NOT EDIT!
*/

const embed_files = {
	'cmd/mkembedfs/mkembedfs.v': $embed_file('cmd/mkembedfs/mkembedfs.v')
}
"
	data := embedfs.generate('cmd', ignore: ['*.txt'])!
	assert data == expected
}
